name: MagicWands
version: '1.0'
main: de.Chaos.magicWands.MagicWands
api-version: '1.21'


commands:
  wandbuilder:
    description: Öffnet das Zauberstab-Bau-GUI
    usage: /wandbuilder
  mw:
    description: Hauptbefehl für MagicWands Plugin
    usage: /mw <wandinfo|givewand> [args...]
    aliases: [magicwands]
